#![doc = "Peripheral access API for MCXA156 microcontrollers (generated using svd2rust v0.37.1 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_cfg))]
#[doc = r"Number available in the NVIC for configuring priority"]
pub const NVIC_PRIO_BITS: u8 = 3;
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
extern "C" {
    fn Reserved16();
    fn CMC();
    fn DMA_CH0();
    fn DMA_CH1();
    fn DMA_CH2();
    fn DMA_CH3();
    fn DMA_CH4();
    fn DMA_CH5();
    fn DMA_CH6();
    fn DMA_CH7();
    fn ERM0_SINGLE_BIT();
    fn ERM0_MULTI_BIT();
    fn FMU0();
    fn GLIKEY0();
    fn MBC0();
    fn SCG0();
    fn SPC0();
    fn VBAT0();
    fn WUU0();
    fn CAN0();
    fn Reserved36();
    fn Reserved37();
    fn Reserved38();
    fn FLEXIO();
    fn I3C0();
    fn Reserved41();
    fn LPI2C0();
    fn LPI2C1();
    fn LPSPI0();
    fn LPSPI1();
    fn Reserved46();
    fn LPUART0();
    fn LPUART1();
    fn LPUART2();
    fn LPUART3();
    fn LPUART4();
    fn USB0();
    fn Reserved53();
    fn CDOG0();
    fn CTIMER0();
    fn CTIMER1();
    fn CTIMER2();
    fn CTIMER3();
    fn CTIMER4();
    fn FLEXPWM0_RELOAD_ERROR();
    fn FLEXPWM0_FAULT();
    fn FLEXPWM0_SUBMODULE0();
    fn FLEXPWM0_SUBMODULE1();
    fn FLEXPWM0_SUBMODULE2();
    fn Reserved65();
    fn QDC0_COMPARE();
    fn QDC0_HOME();
    fn QDC0_WATCHDOG();
    fn QDC0_INDEX();
    fn FREQME0();
    fn LPTMR0();
    fn Reserved72();
    fn OS_EVENT();
    fn WAKETIMER0();
    fn UTICK0();
    fn WWDT0();
    fn Reserved77();
    fn ADC0();
    fn ADC1();
    fn CMP0();
    fn CMP1();
    fn Reserved82();
    fn DAC0();
    fn Reserved84();
    fn Reserved85();
    fn Reserved86();
    fn GPIO0();
    fn GPIO1();
    fn GPIO2();
    fn GPIO3();
    fn GPIO4();
    fn Reserved92();
    fn LPI2C2();
    fn LPI2C3();
    fn FLEXPWM1_RELOAD_ERROR();
    fn FLEXPWM1_FAULT();
    fn FLEXPWM1_SUBMODULE0();
    fn FLEXPWM1_SUBMODULE1();
    fn FLEXPWM1_SUBMODULE2();
    fn Reserved100();
    fn QDC1_COMPARE();
    fn QDC1_HOME();
    fn QDC1_WATCHDOG();
    fn QDC1_INDEX();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
pub static __INTERRUPTS: [Vector; 89] = [
    Vector {
        _handler: Reserved16,
    },
    Vector { _handler: CMC },
    Vector { _handler: DMA_CH0 },
    Vector { _handler: DMA_CH1 },
    Vector { _handler: DMA_CH2 },
    Vector { _handler: DMA_CH3 },
    Vector { _handler: DMA_CH4 },
    Vector { _handler: DMA_CH5 },
    Vector { _handler: DMA_CH6 },
    Vector { _handler: DMA_CH7 },
    Vector {
        _handler: ERM0_SINGLE_BIT,
    },
    Vector {
        _handler: ERM0_MULTI_BIT,
    },
    Vector { _handler: FMU0 },
    Vector { _handler: GLIKEY0 },
    Vector { _handler: MBC0 },
    Vector { _handler: SCG0 },
    Vector { _handler: SPC0 },
    Vector { _handler: VBAT0 },
    Vector { _handler: WUU0 },
    Vector { _handler: CAN0 },
    Vector {
        _handler: Reserved36,
    },
    Vector {
        _handler: Reserved37,
    },
    Vector {
        _handler: Reserved38,
    },
    Vector { _handler: FLEXIO },
    Vector { _handler: I3C0 },
    Vector {
        _handler: Reserved41,
    },
    Vector { _handler: LPI2C0 },
    Vector { _handler: LPI2C1 },
    Vector { _handler: LPSPI0 },
    Vector { _handler: LPSPI1 },
    Vector {
        _handler: Reserved46,
    },
    Vector { _handler: LPUART0 },
    Vector { _handler: LPUART1 },
    Vector { _handler: LPUART2 },
    Vector { _handler: LPUART3 },
    Vector { _handler: LPUART4 },
    Vector { _handler: USB0 },
    Vector {
        _handler: Reserved53,
    },
    Vector { _handler: CDOG0 },
    Vector { _handler: CTIMER0 },
    Vector { _handler: CTIMER1 },
    Vector { _handler: CTIMER2 },
    Vector { _handler: CTIMER3 },
    Vector { _handler: CTIMER4 },
    Vector {
        _handler: FLEXPWM0_RELOAD_ERROR,
    },
    Vector {
        _handler: FLEXPWM0_FAULT,
    },
    Vector {
        _handler: FLEXPWM0_SUBMODULE0,
    },
    Vector {
        _handler: FLEXPWM0_SUBMODULE1,
    },
    Vector {
        _handler: FLEXPWM0_SUBMODULE2,
    },
    Vector {
        _handler: Reserved65,
    },
    Vector {
        _handler: QDC0_COMPARE,
    },
    Vector {
        _handler: QDC0_HOME,
    },
    Vector {
        _handler: QDC0_WATCHDOG,
    },
    Vector {
        _handler: QDC0_INDEX,
    },
    Vector { _handler: FREQME0 },
    Vector { _handler: LPTMR0 },
    Vector {
        _handler: Reserved72,
    },
    Vector { _handler: OS_EVENT },
    Vector {
        _handler: WAKETIMER0,
    },
    Vector { _handler: UTICK0 },
    Vector { _handler: WWDT0 },
    Vector {
        _handler: Reserved77,
    },
    Vector { _handler: ADC0 },
    Vector { _handler: ADC1 },
    Vector { _handler: CMP0 },
    Vector { _handler: CMP1 },
    Vector {
        _handler: Reserved82,
    },
    Vector { _handler: DAC0 },
    Vector {
        _handler: Reserved84,
    },
    Vector {
        _handler: Reserved85,
    },
    Vector {
        _handler: Reserved86,
    },
    Vector { _handler: GPIO0 },
    Vector { _handler: GPIO1 },
    Vector { _handler: GPIO2 },
    Vector { _handler: GPIO3 },
    Vector { _handler: GPIO4 },
    Vector {
        _handler: Reserved92,
    },
    Vector { _handler: LPI2C2 },
    Vector { _handler: LPI2C3 },
    Vector {
        _handler: FLEXPWM1_RELOAD_ERROR,
    },
    Vector {
        _handler: FLEXPWM1_FAULT,
    },
    Vector {
        _handler: FLEXPWM1_SUBMODULE0,
    },
    Vector {
        _handler: FLEXPWM1_SUBMODULE1,
    },
    Vector {
        _handler: FLEXPWM1_SUBMODULE2,
    },
    Vector {
        _handler: Reserved100,
    },
    Vector {
        _handler: QDC1_COMPARE,
    },
    Vector {
        _handler: QDC1_HOME,
    },
    Vector {
        _handler: QDC1_WATCHDOG,
    },
    Vector {
        _handler: QDC1_INDEX,
    },
];
#[doc = r"Enumeration of all the interrupts."]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "0 - Reserved16"]
    Reserved16 = 0,
    #[doc = "1 - CMC"]
    CMC = 1,
    #[doc = "2 - DMA_CH0"]
    DMA_CH0 = 2,
    #[doc = "3 - DMA_CH1"]
    DMA_CH1 = 3,
    #[doc = "4 - DMA_CH2"]
    DMA_CH2 = 4,
    #[doc = "5 - DMA_CH3"]
    DMA_CH3 = 5,
    #[doc = "6 - DMA_CH4"]
    DMA_CH4 = 6,
    #[doc = "7 - DMA_CH5"]
    DMA_CH5 = 7,
    #[doc = "8 - DMA_CH6"]
    DMA_CH6 = 8,
    #[doc = "9 - DMA_CH7"]
    DMA_CH7 = 9,
    #[doc = "10 - ERM0_SINGLE_BIT"]
    ERM0_SINGLE_BIT = 10,
    #[doc = "11 - ERM0_MULTI_BIT"]
    ERM0_MULTI_BIT = 11,
    #[doc = "12 - FMU0"]
    FMU0 = 12,
    #[doc = "13 - GLIKEY0"]
    GLIKEY0 = 13,
    #[doc = "14 - MBC0"]
    MBC0 = 14,
    #[doc = "15 - SCG0"]
    SCG0 = 15,
    #[doc = "16 - SPC0"]
    SPC0 = 16,
    #[doc = "17 - VBAT0"]
    VBAT0 = 17,
    #[doc = "18 - WUU0"]
    WUU0 = 18,
    #[doc = "19 - CAN0"]
    CAN0 = 19,
    #[doc = "20 - Reserved36"]
    Reserved36 = 20,
    #[doc = "21 - Reserved37"]
    Reserved37 = 21,
    #[doc = "22 - Reserved38"]
    Reserved38 = 22,
    #[doc = "23 - FLEXIO"]
    FLEXIO = 23,
    #[doc = "24 - I3C0"]
    I3C0 = 24,
    #[doc = "25 - Reserved41"]
    Reserved41 = 25,
    #[doc = "26 - LPI2C0"]
    LPI2C0 = 26,
    #[doc = "27 - LPI2C1"]
    LPI2C1 = 27,
    #[doc = "28 - LPSPI0"]
    LPSPI0 = 28,
    #[doc = "29 - LPSPI1"]
    LPSPI1 = 29,
    #[doc = "30 - Reserved46"]
    Reserved46 = 30,
    #[doc = "31 - LPUART0"]
    LPUART0 = 31,
    #[doc = "32 - LPUART1"]
    LPUART1 = 32,
    #[doc = "33 - LPUART2"]
    LPUART2 = 33,
    #[doc = "34 - LPUART3"]
    LPUART3 = 34,
    #[doc = "35 - LPUART4"]
    LPUART4 = 35,
    #[doc = "36 - USB0"]
    USB0 = 36,
    #[doc = "37 - Reserved53"]
    Reserved53 = 37,
    #[doc = "38 - CDOG0"]
    CDOG0 = 38,
    #[doc = "39 - CTIMER0"]
    CTIMER0 = 39,
    #[doc = "40 - CTIMER1"]
    CTIMER1 = 40,
    #[doc = "41 - CTIMER2"]
    CTIMER2 = 41,
    #[doc = "42 - CTIMER3"]
    CTIMER3 = 42,
    #[doc = "43 - CTIMER4"]
    CTIMER4 = 43,
    #[doc = "44 - FLEXPWM0_RELOAD_ERROR"]
    FLEXPWM0_RELOAD_ERROR = 44,
    #[doc = "45 - FLEXPWM0_FAULT"]
    FLEXPWM0_FAULT = 45,
    #[doc = "46 - FLEXPWM0_SUBMODULE0"]
    FLEXPWM0_SUBMODULE0 = 46,
    #[doc = "47 - FLEXPWM0_SUBMODULE1"]
    FLEXPWM0_SUBMODULE1 = 47,
    #[doc = "48 - FLEXPWM0_SUBMODULE2"]
    FLEXPWM0_SUBMODULE2 = 48,
    #[doc = "49 - Reserved65"]
    Reserved65 = 49,
    #[doc = "50 - QDC0_COMPARE"]
    QDC0_COMPARE = 50,
    #[doc = "51 - QDC0_HOME"]
    QDC0_HOME = 51,
    #[doc = "52 - QDC0_WATCHDOG"]
    QDC0_WATCHDOG = 52,
    #[doc = "53 - QDC0_INDEX"]
    QDC0_INDEX = 53,
    #[doc = "54 - FREQME0"]
    FREQME0 = 54,
    #[doc = "55 - LPTMR0"]
    LPTMR0 = 55,
    #[doc = "56 - Reserved72"]
    Reserved72 = 56,
    #[doc = "57 - OS_EVENT"]
    OS_EVENT = 57,
    #[doc = "58 - WAKETIMER0"]
    WAKETIMER0 = 58,
    #[doc = "59 - UTICK0"]
    UTICK0 = 59,
    #[doc = "60 - WWDT0"]
    WWDT0 = 60,
    #[doc = "61 - Reserved77"]
    Reserved77 = 61,
    #[doc = "62 - ADC0"]
    ADC0 = 62,
    #[doc = "63 - ADC1"]
    ADC1 = 63,
    #[doc = "64 - CMP0"]
    CMP0 = 64,
    #[doc = "65 - CMP1"]
    CMP1 = 65,
    #[doc = "66 - Reserved82"]
    Reserved82 = 66,
    #[doc = "67 - DAC0"]
    DAC0 = 67,
    #[doc = "68 - Reserved84"]
    Reserved84 = 68,
    #[doc = "69 - Reserved85"]
    Reserved85 = 69,
    #[doc = "70 - Reserved86"]
    Reserved86 = 70,
    #[doc = "71 - GPIO0"]
    GPIO0 = 71,
    #[doc = "72 - GPIO1"]
    GPIO1 = 72,
    #[doc = "73 - GPIO2"]
    GPIO2 = 73,
    #[doc = "74 - GPIO3"]
    GPIO3 = 74,
    #[doc = "75 - GPIO4"]
    GPIO4 = 75,
    #[doc = "76 - Reserved92"]
    Reserved92 = 76,
    #[doc = "77 - LPI2C2"]
    LPI2C2 = 77,
    #[doc = "78 - LPI2C3"]
    LPI2C3 = 78,
    #[doc = "79 - FLEXPWM1_RELOAD_ERROR"]
    FLEXPWM1_RELOAD_ERROR = 79,
    #[doc = "80 - FLEXPWM1_FAULT"]
    FLEXPWM1_FAULT = 80,
    #[doc = "81 - FLEXPWM1_SUBMODULE0"]
    FLEXPWM1_SUBMODULE0 = 81,
    #[doc = "82 - FLEXPWM1_SUBMODULE1"]
    FLEXPWM1_SUBMODULE1 = 82,
    #[doc = "83 - FLEXPWM1_SUBMODULE2"]
    FLEXPWM1_SUBMODULE2 = 83,
    #[doc = "84 - Reserved100"]
    Reserved100 = 84,
    #[doc = "85 - QDC1_COMPARE"]
    QDC1_COMPARE = 85,
    #[doc = "86 - QDC1_HOME"]
    QDC1_HOME = 86,
    #[doc = "87 - QDC1_WATCHDOG"]
    QDC1_WATCHDOG = 87,
    #[doc = "88 - QDC1_INDEX"]
    QDC1_INDEX = 88,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[doc = "INPUTMUX"]
pub type Inputmux0 = crate::Periph<inputmux0::RegisterBlock, 0x4000_1000>;
impl core::fmt::Debug for Inputmux0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Inputmux0").finish()
    }
}
#[doc = "INPUTMUX"]
pub mod inputmux0;
#[doc = "I3C"]
pub type I3c0 = crate::Periph<i3c0::RegisterBlock, 0x4000_2000>;
impl core::fmt::Debug for I3c0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I3c0").finish()
    }
}
#[doc = "I3C"]
pub mod i3c0;
#[doc = "CTIMER"]
pub type Ctimer0 = crate::Periph<ctimer0::RegisterBlock, 0x4000_4000>;
impl core::fmt::Debug for Ctimer0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ctimer0").finish()
    }
}
#[doc = "CTIMER"]
pub mod ctimer0;
#[doc = "CTIMER"]
pub type Ctimer1 = crate::Periph<ctimer0::RegisterBlock, 0x4000_5000>;
impl core::fmt::Debug for Ctimer1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ctimer1").finish()
    }
}
#[doc = "CTIMER"]
pub use self::ctimer0 as ctimer1;
#[doc = "CTIMER"]
pub type Ctimer2 = crate::Periph<ctimer0::RegisterBlock, 0x4000_6000>;
impl core::fmt::Debug for Ctimer2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ctimer2").finish()
    }
}
#[doc = "CTIMER"]
pub use self::ctimer0 as ctimer2;
#[doc = "CTIMER"]
pub type Ctimer3 = crate::Periph<ctimer0::RegisterBlock, 0x4000_7000>;
impl core::fmt::Debug for Ctimer3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ctimer3").finish()
    }
}
#[doc = "CTIMER"]
pub use self::ctimer0 as ctimer3;
#[doc = "CTIMER"]
pub type Ctimer4 = crate::Periph<ctimer0::RegisterBlock, 0x4000_8000>;
impl core::fmt::Debug for Ctimer4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ctimer4").finish()
    }
}
#[doc = "CTIMER"]
pub use self::ctimer0 as ctimer4;
#[doc = "FREQME"]
pub type Freqme0 = crate::Periph<freqme0::RegisterBlock, 0x4000_9000>;
impl core::fmt::Debug for Freqme0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Freqme0").finish()
    }
}
#[doc = "FREQME"]
pub mod freqme0;
#[doc = "UTICK"]
pub type Utick0 = crate::Periph<utick0::RegisterBlock, 0x4000_b000>;
impl core::fmt::Debug for Utick0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Utick0").finish()
    }
}
#[doc = "UTICK"]
pub mod utick0;
#[doc = "WWDT"]
pub type Wwdt0 = crate::Periph<wwdt0::RegisterBlock, 0x4000_c000>;
impl core::fmt::Debug for Wwdt0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Wwdt0").finish()
    }
}
#[doc = "WWDT"]
pub mod wwdt0;
#[doc = "DMA MP"]
pub type Dma0 = crate::Periph<dma0::RegisterBlock, 0x4008_0000>;
impl core::fmt::Debug for Dma0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dma0").finish()
    }
}
#[doc = "DMA MP"]
pub mod dma0;
#[doc = "DMA TCD"]
pub type Edma0Tcd0 = crate::Periph<edma_0_tcd0::RegisterBlock, 0x4008_1000>;
impl core::fmt::Debug for Edma0Tcd0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Edma0Tcd0").finish()
    }
}
#[doc = "DMA TCD"]
pub mod edma_0_tcd0;
#[doc = "AOI"]
pub type Aoi0 = crate::Periph<aoi0::RegisterBlock, 0x4008_9000>;
impl core::fmt::Debug for Aoi0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Aoi0").finish()
    }
}
#[doc = "AOI"]
pub mod aoi0;
#[doc = "AOI"]
pub type Aoi1 = crate::Periph<aoi0::RegisterBlock, 0x4009_7000>;
impl core::fmt::Debug for Aoi1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Aoi1").finish()
    }
}
#[doc = "AOI"]
pub use self::aoi0 as aoi1;
#[doc = "CRC"]
pub type Crc0 = crate::Periph<crc0::RegisterBlock, 0x4008_a000>;
impl core::fmt::Debug for Crc0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Crc0").finish()
    }
}
#[doc = "CRC"]
pub mod crc0;
#[doc = "CMC"]
pub type Cmc = crate::Periph<cmc::RegisterBlock, 0x4008_b000>;
impl core::fmt::Debug for Cmc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cmc").finish()
    }
}
#[doc = "CMC"]
pub mod cmc;
#[doc = "EIM"]
pub type Eim0 = crate::Periph<eim0::RegisterBlock, 0x4008_c000>;
impl core::fmt::Debug for Eim0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Eim0").finish()
    }
}
#[doc = "EIM"]
pub mod eim0;
#[doc = "ERM"]
pub type Erm0 = crate::Periph<erm0::RegisterBlock, 0x4008_d000>;
impl core::fmt::Debug for Erm0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Erm0").finish()
    }
}
#[doc = "ERM"]
pub mod erm0;
#[doc = "TRDC"]
pub type Mbc0 = crate::Periph<mbc0::RegisterBlock, 0x4008_e000>;
impl core::fmt::Debug for Mbc0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Mbc0").finish()
    }
}
#[doc = "TRDC"]
pub mod mbc0;
#[doc = "SCG"]
pub type Scg0 = crate::Periph<scg0::RegisterBlock, 0x4008_f000>;
impl core::fmt::Debug for Scg0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Scg0").finish()
    }
}
#[doc = "SCG"]
pub mod scg0;
#[doc = "SPC"]
pub type Spc0 = crate::Periph<spc0::RegisterBlock, 0x4009_0000>;
impl core::fmt::Debug for Spc0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spc0").finish()
    }
}
#[doc = "SPC"]
pub mod spc0;
#[doc = "MRCC"]
pub type Mrcc0 = crate::Periph<mrcc0::RegisterBlock, 0x4009_1000>;
impl core::fmt::Debug for Mrcc0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Mrcc0").finish()
    }
}
#[doc = "MRCC"]
pub mod mrcc0;
#[doc = "SYSCON"]
pub type Syscon = crate::Periph<syscon::RegisterBlock, 0x4009_1000>;
impl core::fmt::Debug for Syscon {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Syscon").finish()
    }
}
#[doc = "SYSCON"]
pub mod syscon;
#[doc = "GLIKEY"]
pub type Glikey0 = crate::Periph<glikey0::RegisterBlock, 0x4009_1d00>;
impl core::fmt::Debug for Glikey0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Glikey0").finish()
    }
}
#[doc = "GLIKEY"]
pub mod glikey0;
#[doc = "Low-Leakage Wakeup Unit"]
pub type Wuu0 = crate::Periph<wuu0::RegisterBlock, 0x4009_2000>;
impl core::fmt::Debug for Wuu0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Wuu0").finish()
    }
}
#[doc = "Low-Leakage Wakeup Unit"]
pub mod wuu0;
#[doc = "VBAT"]
pub type Vbat0 = crate::Periph<vbat0::RegisterBlock, 0x4009_3000>;
impl core::fmt::Debug for Vbat0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Vbat0").finish()
    }
}
#[doc = "VBAT"]
pub mod vbat0;
#[doc = "NPX"]
pub type Fmc0 = crate::Periph<fmc0::RegisterBlock, 0x4009_4000>;
impl core::fmt::Debug for Fmc0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Fmc0").finish()
    }
}
#[doc = "NPX"]
pub mod fmc0;
#[doc = "Flash"]
pub type Fmu0 = crate::Periph<fmu0::RegisterBlock, 0x4009_5000>;
impl core::fmt::Debug for Fmu0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Fmu0").finish()
    }
}
#[doc = "Flash"]
pub mod fmu0;
#[doc = "FlashTest"]
pub type Fmu0test = crate::Periph<fmu0test::RegisterBlock, 0x4009_6000>;
impl core::fmt::Debug for Fmu0test {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Fmu0test").finish()
    }
}
#[doc = "FlashTest"]
pub mod fmu0test;
#[doc = "FLEXIO"]
pub type Flexio0 = crate::Periph<flexio0::RegisterBlock, 0x4009_9000>;
impl core::fmt::Debug for Flexio0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Flexio0").finish()
    }
}
#[doc = "FLEXIO"]
pub mod flexio0;
#[doc = "Low-Power Inter-Integrated Circuit"]
pub type Lpi2c0 = crate::Periph<lpi2c0::RegisterBlock, 0x4009_a000>;
impl core::fmt::Debug for Lpi2c0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Lpi2c0").finish()
    }
}
#[doc = "Low-Power Inter-Integrated Circuit"]
pub mod lpi2c0;
#[doc = "Low-Power Inter-Integrated Circuit"]
pub type Lpi2c1 = crate::Periph<lpi2c0::RegisterBlock, 0x4009_b000>;
impl core::fmt::Debug for Lpi2c1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Lpi2c1").finish()
    }
}
#[doc = "Low-Power Inter-Integrated Circuit"]
pub use self::lpi2c0 as lpi2c1;
#[doc = "Low-Power Inter-Integrated Circuit"]
pub type Lpi2c2 = crate::Periph<lpi2c0::RegisterBlock, 0x400d_4000>;
impl core::fmt::Debug for Lpi2c2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Lpi2c2").finish()
    }
}
#[doc = "Low-Power Inter-Integrated Circuit"]
pub use self::lpi2c0 as lpi2c2;
#[doc = "Low-Power Inter-Integrated Circuit"]
pub type Lpi2c3 = crate::Periph<lpi2c0::RegisterBlock, 0x400d_5000>;
impl core::fmt::Debug for Lpi2c3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Lpi2c3").finish()
    }
}
#[doc = "Low-Power Inter-Integrated Circuit"]
pub use self::lpi2c0 as lpi2c3;
#[doc = "Low-Power Serial Peripheral Interface"]
pub type Lpspi0 = crate::Periph<lpspi0::RegisterBlock, 0x4009_c000>;
impl core::fmt::Debug for Lpspi0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Lpspi0").finish()
    }
}
#[doc = "Low-Power Serial Peripheral Interface"]
pub mod lpspi0;
#[doc = "Low-Power Serial Peripheral Interface"]
pub type Lpspi1 = crate::Periph<lpspi0::RegisterBlock, 0x4009_d000>;
impl core::fmt::Debug for Lpspi1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Lpspi1").finish()
    }
}
#[doc = "Low-Power Serial Peripheral Interface"]
pub use self::lpspi0 as lpspi1;
#[doc = "LPUART"]
pub type Lpuart0 = crate::Periph<lpuart0::RegisterBlock, 0x4009_f000>;
impl core::fmt::Debug for Lpuart0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Lpuart0").finish()
    }
}
#[doc = "LPUART"]
pub mod lpuart0;
#[doc = "LPUART"]
pub type Lpuart1 = crate::Periph<lpuart0::RegisterBlock, 0x400a_0000>;
impl core::fmt::Debug for Lpuart1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Lpuart1").finish()
    }
}
#[doc = "LPUART"]
pub use self::lpuart0 as lpuart1;
#[doc = "LPUART"]
pub type Lpuart2 = crate::Periph<lpuart0::RegisterBlock, 0x400a_1000>;
impl core::fmt::Debug for Lpuart2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Lpuart2").finish()
    }
}
#[doc = "LPUART"]
pub use self::lpuart0 as lpuart2;
#[doc = "LPUART"]
pub type Lpuart3 = crate::Periph<lpuart0::RegisterBlock, 0x400a_2000>;
impl core::fmt::Debug for Lpuart3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Lpuart3").finish()
    }
}
#[doc = "LPUART"]
pub use self::lpuart0 as lpuart3;
#[doc = "LPUART"]
pub type Lpuart4 = crate::Periph<lpuart0::RegisterBlock, 0x400a_3000>;
impl core::fmt::Debug for Lpuart4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Lpuart4").finish()
    }
}
#[doc = "LPUART"]
pub use self::lpuart0 as lpuart4;
#[doc = "USBFS"]
pub type Usb0 = crate::Periph<usb0::RegisterBlock, 0x400a_4000>;
impl core::fmt::Debug for Usb0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usb0").finish()
    }
}
#[doc = "USBFS"]
pub mod usb0;
#[doc = "Quadrature_Decoder"]
pub type Qdc0 = crate::Periph<qdc0::RegisterBlock, 0x400a_7000>;
impl core::fmt::Debug for Qdc0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Qdc0").finish()
    }
}
#[doc = "Quadrature_Decoder"]
pub mod qdc0;
#[doc = "Quadrature_Decoder"]
pub type Qdc1 = crate::Periph<qdc0::RegisterBlock, 0x400a_8000>;
impl core::fmt::Debug for Qdc1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Qdc1").finish()
    }
}
#[doc = "Quadrature_Decoder"]
pub use self::qdc0 as qdc1;
#[doc = "PWM"]
pub type Flexpwm0 = crate::Periph<flexpwm0::RegisterBlock, 0x400a_9000>;
impl core::fmt::Debug for Flexpwm0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Flexpwm0").finish()
    }
}
#[doc = "PWM"]
pub mod flexpwm0;
#[doc = "PWM"]
pub type Flexpwm1 = crate::Periph<flexpwm0::RegisterBlock, 0x400a_a000>;
impl core::fmt::Debug for Flexpwm1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Flexpwm1").finish()
    }
}
#[doc = "PWM"]
pub use self::flexpwm0 as flexpwm1;
#[doc = "LPTMR"]
pub type Lptmr0 = crate::Periph<lptmr0::RegisterBlock, 0x400a_b000>;
impl core::fmt::Debug for Lptmr0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Lptmr0").finish()
    }
}
#[doc = "LPTMR"]
pub mod lptmr0;
#[doc = "OSTIMER"]
pub type Ostimer0 = crate::Periph<ostimer0::RegisterBlock, 0x400a_d000>;
impl core::fmt::Debug for Ostimer0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ostimer0").finish()
    }
}
#[doc = "OSTIMER"]
pub mod ostimer0;
#[doc = "WAKEUP_TIMER"]
pub type Waketimer0 = crate::Periph<waketimer0::RegisterBlock, 0x400a_e000>;
impl core::fmt::Debug for Waketimer0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Waketimer0").finish()
    }
}
#[doc = "WAKEUP_TIMER"]
pub mod waketimer0;
#[doc = "ADC"]
pub type Adc0 = crate::Periph<adc0::RegisterBlock, 0x400a_f000>;
impl core::fmt::Debug for Adc0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Adc0").finish()
    }
}
#[doc = "ADC"]
pub mod adc0;
#[doc = "ADC"]
pub type Adc1 = crate::Periph<adc0::RegisterBlock, 0x400b_0000>;
impl core::fmt::Debug for Adc1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Adc1").finish()
    }
}
#[doc = "ADC"]
pub use self::adc0 as adc1;
#[doc = "LPCMP"]
pub type Cmp0 = crate::Periph<cmp0::RegisterBlock, 0x400b_1000>;
impl core::fmt::Debug for Cmp0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cmp0").finish()
    }
}
#[doc = "LPCMP"]
pub mod cmp0;
#[doc = "LPCMP"]
pub type Cmp1 = crate::Periph<cmp0::RegisterBlock, 0x400b_2000>;
impl core::fmt::Debug for Cmp1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cmp1").finish()
    }
}
#[doc = "LPCMP"]
pub use self::cmp0 as cmp1;
#[doc = "12-bit DAC"]
pub type Dac0 = crate::Periph<dac0::RegisterBlock, 0x400b_4000>;
impl core::fmt::Debug for Dac0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dac0").finish()
    }
}
#[doc = "12-bit DAC"]
pub mod dac0;
#[doc = "OPAMP"]
pub type Opamp0 = crate::Periph<opamp0::RegisterBlock, 0x400b_7000>;
impl core::fmt::Debug for Opamp0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Opamp0").finish()
    }
}
#[doc = "OPAMP"]
pub mod opamp0;
#[doc = "PORT"]
pub type Port0 = crate::Periph<port0::RegisterBlock, 0x400b_c000>;
impl core::fmt::Debug for Port0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Port0").finish()
    }
}
#[doc = "PORT"]
pub mod port0;
#[doc = "PORT"]
pub type Port1 = crate::Periph<port1::RegisterBlock, 0x400b_d000>;
impl core::fmt::Debug for Port1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Port1").finish()
    }
}
#[doc = "PORT"]
pub mod port1;
#[doc = "PORT"]
pub type Port2 = crate::Periph<port2::RegisterBlock, 0x400b_e000>;
impl core::fmt::Debug for Port2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Port2").finish()
    }
}
#[doc = "PORT"]
pub mod port2;
#[doc = "PORT"]
pub type Port3 = crate::Periph<port3::RegisterBlock, 0x400b_f000>;
impl core::fmt::Debug for Port3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Port3").finish()
    }
}
#[doc = "PORT"]
pub mod port3;
#[doc = "PORT"]
pub type Port4 = crate::Periph<port4::RegisterBlock, 0x400c_0000>;
impl core::fmt::Debug for Port4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Port4").finish()
    }
}
#[doc = "PORT"]
pub mod port4;
#[doc = "CAN"]
pub type Can0 = crate::Periph<can0::RegisterBlock, 0x400c_c000>;
impl core::fmt::Debug for Can0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Can0").finish()
    }
}
#[doc = "CAN"]
pub mod can0;
#[doc = "CDOG"]
pub type Cdog = crate::Periph<cdog::RegisterBlock, 0x4010_0000>;
impl core::fmt::Debug for Cdog {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cdog").finish()
    }
}
#[doc = "CDOG"]
pub mod cdog;
#[doc = "DBGMB"]
pub type Dbgmailbox = crate::Periph<dbgmailbox::RegisterBlock, 0x4010_1000>;
impl core::fmt::Debug for Dbgmailbox {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dbgmailbox").finish()
    }
}
#[doc = "DBGMB"]
pub mod dbgmailbox;
#[doc = "GPIO"]
pub type Gpio0 = crate::Periph<gpio0::RegisterBlock, 0x4010_2000>;
impl core::fmt::Debug for Gpio0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpio0").finish()
    }
}
#[doc = "GPIO"]
pub mod gpio0;
#[doc = "GPIO"]
pub type Gpio1 = crate::Periph<gpio0::RegisterBlock, 0x4010_3000>;
impl core::fmt::Debug for Gpio1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpio1").finish()
    }
}
#[doc = "GPIO"]
pub use self::gpio0 as gpio1;
#[doc = "GPIO"]
pub type Gpio2 = crate::Periph<gpio0::RegisterBlock, 0x4010_4000>;
impl core::fmt::Debug for Gpio2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpio2").finish()
    }
}
#[doc = "GPIO"]
pub use self::gpio0 as gpio2;
#[doc = "GPIO"]
pub type Gpio3 = crate::Periph<gpio0::RegisterBlock, 0x4010_5000>;
impl core::fmt::Debug for Gpio3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpio3").finish()
    }
}
#[doc = "GPIO"]
pub use self::gpio0 as gpio3;
#[doc = "GPIO"]
pub type Gpio4 = crate::Periph<gpio0::RegisterBlock, 0x4010_6000>;
impl core::fmt::Debug for Gpio4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpio4").finish()
    }
}
#[doc = "GPIO"]
pub use self::gpio0 as gpio4;
#[doc = "System Control not in System Control Block"]
pub type ScnScb = crate::Periph<scn_scb::RegisterBlock, 0xe000_e000>;
impl core::fmt::Debug for ScnScb {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("ScnScb").finish()
    }
}
#[doc = "System Control not in System Control Block"]
pub mod scn_scb;
#[doc = "M33 Systick module"]
pub type SysTick = crate::Periph<sys_tick::RegisterBlock, 0xe000_e010>;
impl core::fmt::Debug for SysTick {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SysTick").finish()
    }
}
#[doc = "M33 Systick module"]
pub mod sys_tick;
#[doc = "Security Attribution Unit"]
pub type Sau = crate::Periph<sau::RegisterBlock, 0xe000_edd0>;
impl core::fmt::Debug for Sau {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sau").finish()
    }
}
#[doc = "Security Attribution Unit"]
pub mod sau;
#[unsafe(no_mangle)]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "INPUTMUX0"]
    pub inputmux0: Inputmux0,
    #[doc = "I3C0"]
    pub i3c0: I3c0,
    #[doc = "CTIMER0"]
    pub ctimer0: Ctimer0,
    #[doc = "CTIMER1"]
    pub ctimer1: Ctimer1,
    #[doc = "CTIMER2"]
    pub ctimer2: Ctimer2,
    #[doc = "CTIMER3"]
    pub ctimer3: Ctimer3,
    #[doc = "CTIMER4"]
    pub ctimer4: Ctimer4,
    #[doc = "FREQME0"]
    pub freqme0: Freqme0,
    #[doc = "UTICK0"]
    pub utick0: Utick0,
    #[doc = "WWDT0"]
    pub wwdt0: Wwdt0,
    #[doc = "DMA0"]
    pub dma0: Dma0,
    #[doc = "EDMA_0_TCD0"]
    pub edma_0_tcd0: Edma0Tcd0,
    #[doc = "AOI0"]
    pub aoi0: Aoi0,
    #[doc = "AOI1"]
    pub aoi1: Aoi1,
    #[doc = "CRC0"]
    pub crc0: Crc0,
    #[doc = "CMC"]
    pub cmc: Cmc,
    #[doc = "EIM0"]
    pub eim0: Eim0,
    #[doc = "ERM0"]
    pub erm0: Erm0,
    #[doc = "MBC0"]
    pub mbc0: Mbc0,
    #[doc = "SCG0"]
    pub scg0: Scg0,
    #[doc = "SPC0"]
    pub spc0: Spc0,
    #[doc = "MRCC0"]
    pub mrcc0: Mrcc0,
    #[doc = "SYSCON"]
    pub syscon: Syscon,
    #[doc = "GLIKEY0"]
    pub glikey0: Glikey0,
    #[doc = "WUU0"]
    pub wuu0: Wuu0,
    #[doc = "VBAT0"]
    pub vbat0: Vbat0,
    #[doc = "FMC0"]
    pub fmc0: Fmc0,
    #[doc = "FMU0"]
    pub fmu0: Fmu0,
    #[doc = "FMU0TEST"]
    pub fmu0test: Fmu0test,
    #[doc = "FLEXIO0"]
    pub flexio0: Flexio0,
    #[doc = "LPI2C0"]
    pub lpi2c0: Lpi2c0,
    #[doc = "LPI2C1"]
    pub lpi2c1: Lpi2c1,
    #[doc = "LPI2C2"]
    pub lpi2c2: Lpi2c2,
    #[doc = "LPI2C3"]
    pub lpi2c3: Lpi2c3,
    #[doc = "LPSPI0"]
    pub lpspi0: Lpspi0,
    #[doc = "LPSPI1"]
    pub lpspi1: Lpspi1,
    #[doc = "LPUART0"]
    pub lpuart0: Lpuart0,
    #[doc = "LPUART1"]
    pub lpuart1: Lpuart1,
    #[doc = "LPUART2"]
    pub lpuart2: Lpuart2,
    #[doc = "LPUART3"]
    pub lpuart3: Lpuart3,
    #[doc = "LPUART4"]
    pub lpuart4: Lpuart4,
    #[doc = "USB0"]
    pub usb0: Usb0,
    #[doc = "QDC0"]
    pub qdc0: Qdc0,
    #[doc = "QDC1"]
    pub qdc1: Qdc1,
    #[doc = "FLEXPWM0"]
    pub flexpwm0: Flexpwm0,
    #[doc = "FLEXPWM1"]
    pub flexpwm1: Flexpwm1,
    #[doc = "LPTMR0"]
    pub lptmr0: Lptmr0,
    #[doc = "OSTIMER0"]
    pub ostimer0: Ostimer0,
    #[doc = "WAKETIMER0"]
    pub waketimer0: Waketimer0,
    #[doc = "ADC0"]
    pub adc0: Adc0,
    #[doc = "ADC1"]
    pub adc1: Adc1,
    #[doc = "CMP0"]
    pub cmp0: Cmp0,
    #[doc = "CMP1"]
    pub cmp1: Cmp1,
    #[doc = "DAC0"]
    pub dac0: Dac0,
    #[doc = "OPAMP0"]
    pub opamp0: Opamp0,
    #[doc = "PORT0"]
    pub port0: Port0,
    #[doc = "PORT1"]
    pub port1: Port1,
    #[doc = "PORT2"]
    pub port2: Port2,
    #[doc = "PORT3"]
    pub port3: Port3,
    #[doc = "PORT4"]
    pub port4: Port4,
    #[doc = "CAN0"]
    pub can0: Can0,
    #[doc = "CDOG"]
    pub cdog: Cdog,
    #[doc = "DBGMAILBOX"]
    pub dbgmailbox: Dbgmailbox,
    #[doc = "GPIO0"]
    pub gpio0: Gpio0,
    #[doc = "GPIO1"]
    pub gpio1: Gpio1,
    #[doc = "GPIO2"]
    pub gpio2: Gpio2,
    #[doc = "GPIO3"]
    pub gpio3: Gpio3,
    #[doc = "GPIO4"]
    pub gpio4: Gpio4,
    #[doc = "SCnSCB"]
    pub scn_scb: ScnScb,
    #[doc = "SysTick"]
    pub sys_tick: SysTick,
    #[doc = "SAU"]
    pub sau: Sau,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            inputmux0: Inputmux0::steal(),
            i3c0: I3c0::steal(),
            ctimer0: Ctimer0::steal(),
            ctimer1: Ctimer1::steal(),
            ctimer2: Ctimer2::steal(),
            ctimer3: Ctimer3::steal(),
            ctimer4: Ctimer4::steal(),
            freqme0: Freqme0::steal(),
            utick0: Utick0::steal(),
            wwdt0: Wwdt0::steal(),
            dma0: Dma0::steal(),
            edma_0_tcd0: Edma0Tcd0::steal(),
            aoi0: Aoi0::steal(),
            aoi1: Aoi1::steal(),
            crc0: Crc0::steal(),
            cmc: Cmc::steal(),
            eim0: Eim0::steal(),
            erm0: Erm0::steal(),
            mbc0: Mbc0::steal(),
            scg0: Scg0::steal(),
            spc0: Spc0::steal(),
            mrcc0: Mrcc0::steal(),
            syscon: Syscon::steal(),
            glikey0: Glikey0::steal(),
            wuu0: Wuu0::steal(),
            vbat0: Vbat0::steal(),
            fmc0: Fmc0::steal(),
            fmu0: Fmu0::steal(),
            fmu0test: Fmu0test::steal(),
            flexio0: Flexio0::steal(),
            lpi2c0: Lpi2c0::steal(),
            lpi2c1: Lpi2c1::steal(),
            lpi2c2: Lpi2c2::steal(),
            lpi2c3: Lpi2c3::steal(),
            lpspi0: Lpspi0::steal(),
            lpspi1: Lpspi1::steal(),
            lpuart0: Lpuart0::steal(),
            lpuart1: Lpuart1::steal(),
            lpuart2: Lpuart2::steal(),
            lpuart3: Lpuart3::steal(),
            lpuart4: Lpuart4::steal(),
            usb0: Usb0::steal(),
            qdc0: Qdc0::steal(),
            qdc1: Qdc1::steal(),
            flexpwm0: Flexpwm0::steal(),
            flexpwm1: Flexpwm1::steal(),
            lptmr0: Lptmr0::steal(),
            ostimer0: Ostimer0::steal(),
            waketimer0: Waketimer0::steal(),
            adc0: Adc0::steal(),
            adc1: Adc1::steal(),
            cmp0: Cmp0::steal(),
            cmp1: Cmp1::steal(),
            dac0: Dac0::steal(),
            opamp0: Opamp0::steal(),
            port0: Port0::steal(),
            port1: Port1::steal(),
            port2: Port2::steal(),
            port3: Port3::steal(),
            port4: Port4::steal(),
            can0: Can0::steal(),
            cdog: Cdog::steal(),
            dbgmailbox: Dbgmailbox::steal(),
            gpio0: Gpio0::steal(),
            gpio1: Gpio1::steal(),
            gpio2: Gpio2::steal(),
            gpio3: Gpio3::steal(),
            gpio4: Gpio4::steal(),
            scn_scb: ScnScb::steal(),
            sys_tick: SysTick::steal(),
            sau: Sau::steal(),
        }
    }
}
